# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\temp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data(object):
    def setupUi(self, Data):
        Data.setObjectName("Data")
        Data.resize(869, 877)
        self.gridLayout = QtWidgets.QGridLayout(Data)
        self.gridLayout.setObjectName("gridLayout")
        self.WEBFrame = QtWidgets.QFrame(Data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WEBFrame.sizePolicy().hasHeightForWidth())
        self.WEBFrame.setSizePolicy(sizePolicy)
        self.WEBFrame.setMaximumSize(QtCore.QSize(500, 800))
        self.WEBFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WEBFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WEBFrame.setObjectName("WEBFrame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.WEBFrame)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Reload = QtWidgets.QPushButton(self.WEBFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reload.sizePolicy().hasHeightForWidth())
        self.Reload.setSizePolicy(sizePolicy)
        self.Reload.setMaximumSize(QtCore.QSize(28, 28))
        self.Reload.setObjectName("Reload")
        self.gridLayout_8.addWidget(self.Reload, 2, 4, 1, 1)
        self.WEBLineEdit = QtWidgets.QLineEdit(self.WEBFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WEBLineEdit.sizePolicy().hasHeightForWidth())
        self.WEBLineEdit.setSizePolicy(sizePolicy)
        self.WEBLineEdit.setMaximumSize(QtCore.QSize(36, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.WEBLineEdit.setFont(font)
        self.WEBLineEdit.setObjectName("WEBLineEdit")
        self.gridLayout_8.addWidget(self.WEBLineEdit, 2, 0, 1, 1)
        self.Back = QtWidgets.QPushButton(self.WEBFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMaximumSize(QtCore.QSize(28, 28))
        self.Back.setObjectName("Back")
        self.gridLayout_8.addWidget(self.Back, 2, 2, 1, 1)
        self.Enter = QtWidgets.QPushButton(self.WEBFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Enter.sizePolicy().hasHeightForWidth())
        self.Enter.setSizePolicy(sizePolicy)
        self.Enter.setMaximumSize(QtCore.QSize(53, 28))
        self.Enter.setObjectName("Enter")
        self.gridLayout_8.addWidget(self.Enter, 2, 5, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.WEBFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(500, 800))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.WEBWidgetContents = QtWidgets.QWidget()
        self.WEBWidgetContents.setGeometry(QtCore.QRect(0, 0, 496, 769))
        self.WEBWidgetContents.setObjectName("WEBWidgetContents")
        self.scrollArea_2.setWidget(self.WEBWidgetContents)
        self.gridLayout_8.addWidget(self.scrollArea_2, 1, 0, 1, 6)
        self.gridLayout.addWidget(self.WEBFrame, 0, 0, 1, 1)

        self.retranslateUi(Data)
        QtCore.QMetaObject.connectSlotsByName(Data)

    def retranslateUi(self, Data):
        _translate = QtCore.QCoreApplication.translate
        Data.setWindowTitle(_translate("Data", "Form"))
        self.Reload.setText(_translate("Data", "Re"))
        self.Back.setText(_translate("Data", "<"))
        self.Enter.setText(_translate("Data", "Enter"))
