# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\temp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data(object):
    def setupUi(self, Data):
        Data.setObjectName("Data")
        Data.resize(415, 348)
        self.gridLayout = QtWidgets.QGridLayout(Data)
        self.gridLayout.setObjectName("gridLayout")
        self.DataWidget = QtWidgets.QTableWidget(Data)
        self.DataWidget.setObjectName("DataWidget")
        self.DataWidget.setColumnCount(1)
        self.DataWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataWidget.setItem(4, 0, item)
        self.gridLayout.addWidget(self.DataWidget, 0, 0, 1, 1)

        self.retranslateUi(Data)
        QtCore.QMetaObject.connectSlotsByName(Data)

    def retranslateUi(self, Data):
        _translate = QtCore.QCoreApplication.translate
        Data.setWindowTitle(_translate("Data", "Form"))
        item = self.DataWidget.verticalHeaderItem(0)
        item.setText(_translate("Data", "AppPos"))
        item = self.DataWidget.verticalHeaderItem(1)
        item.setText(_translate("Data", "StopFuntion"))
        item = self.DataWidget.verticalHeaderItem(2)
        item.setText(_translate("Data", "FightCount"))
        item = self.DataWidget.verticalHeaderItem(3)
        item.setText(_translate("Data", "TypeSelect"))
        item = self.DataWidget.verticalHeaderItem(4)
        item.setText(_translate("Data", "RunFlag"))
        item = self.DataWidget.horizontalHeaderItem(0)
        item.setText(_translate("Data", "Value"))
        __sortingEnabled = self.DataWidget.isSortingEnabled()
        self.DataWidget.setSortingEnabled(False)
        item = self.DataWidget.item(1, 0)
        item.setText(_translate("Data", "0"))
        item = self.DataWidget.item(2, 0)
        item.setText(_translate("Data", "0"))
        item = self.DataWidget.item(3, 0)
        item.setText(_translate("Data", "0"))
        item = self.DataWidget.item(4, 0)
        item.setText(_translate("Data", "0"))
        self.DataWidget.setSortingEnabled(__sortingEnabled)
