# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SettingForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingForm(object):
    def setupUi(self, SettingForm):
        SettingForm.setObjectName("SettingForm")
        SettingForm.resize(446, 327)
        self.gridLayout = QtWidgets.QGridLayout(SettingForm)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(SettingForm)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.ScreenWH = QtWidgets.QPushButton(SettingForm)
        self.ScreenWH.setObjectName("ScreenWH")
        self.gridLayout_2.addWidget(self.ScreenWH, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(SettingForm)
        QtCore.QMetaObject.connectSlotsByName(SettingForm)

    def retranslateUi(self, SettingForm):
        _translate = QtCore.QCoreApplication.translate
        SettingForm.setWindowTitle(_translate("SettingForm", "選擇執行單元"))
        self.pushButton_2.setText(_translate("SettingForm", "取消"))
        self.ScreenWH.setText(_translate("SettingForm", "調整視窗"))
