# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SettingForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingForm(object):
    def setupUi(self, SettingForm):
        SettingForm.setObjectName("SettingForm")
        SettingForm.resize(246, 80)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(SettingForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.OpenCatch = QtWidgets.QPushButton(SettingForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OpenCatch.setFont(font)
        self.OpenCatch.setObjectName("OpenCatch")
        self.gridLayout.addWidget(self.OpenCatch, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(SettingForm)
        self.label_2.setMaximumSize(QtCore.QSize(31, 38))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.CatchBrowser = QtWidgets.QTextBrowser(SettingForm)
        self.CatchBrowser.setMaximumSize(QtCore.QSize(81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CatchBrowser.setFont(font)
        self.CatchBrowser.setObjectName("CatchBrowser")
        self.gridLayout.addWidget(self.CatchBrowser, 0, 1, 1, 1)
        self.ClearCookie = QtWidgets.QPushButton(SettingForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ClearCookie.setFont(font)
        self.ClearCookie.setObjectName("ClearCookie")
        self.gridLayout.addWidget(self.ClearCookie, 3, 1, 1, 1)
        self.ScreenWH = QtWidgets.QPushButton(SettingForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScreenWH.setFont(font)
        self.ScreenWH.setObjectName("ScreenWH")
        self.gridLayout.addWidget(self.ScreenWH, 2, 0, 1, 1)
        self.ClearCatch = QtWidgets.QPushButton(SettingForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ClearCatch.setFont(font)
        self.ClearCatch.setObjectName("ClearCatch")
        self.gridLayout.addWidget(self.ClearCatch, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SettingForm)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.Reload = QtWidgets.QPushButton(SettingForm)
        self.Reload.setMaximumSize(QtCore.QSize(25, 25))
        self.Reload.setText("")
        self.Reload.setObjectName("Reload")
        self.gridLayout.addWidget(self.Reload, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(SettingForm)
        QtCore.QMetaObject.connectSlotsByName(SettingForm)

    def retranslateUi(self, SettingForm):
        _translate = QtCore.QCoreApplication.translate
        SettingForm.setWindowTitle(_translate("SettingForm", "視窗設定"))
        self.label.setText(_translate("SettingForm", "快取大小"))
        self.OpenCatch.setText(_translate("SettingForm", "快取位置"))
        self.label_2.setText(_translate("SettingForm", "MB"))
        self.CatchBrowser.setHtml(_translate("SettingForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ClearCookie.setText(_translate("SettingForm", "清除cookie"))
        self.ScreenWH.setText(_translate("SettingForm", "調整視窗"))
        self.ClearCatch.setText(_translate("SettingForm", "清除快取"))
        self.label_3.setText(_translate("SettingForm", "V0.1"))
